version: '3.8'

services:
  backend:
    build:
      context: ./personal-library-be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./personal-library-fe
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
